let WIDTH = 800 ;
let HEIGHT = 600 ;
let totoro; 
let backImg;
let dust; 
let food; 
let dustTo;
let drawPlayer = true;
let speed =2;
let secondLevel;
let enemydust;
let thirdLevel;
let canvas;
let umbrella;
let boostStatus=false;
let timer;